-- phpMyAdmin SQL Dump
-- version 5.2.0
-- https://www.phpmyadmin.net/
--
-- Host: 127.0.0.1
-- Generation Time: Feb 20, 2023 at 12:20 PM
-- Server version: 10.4.27-MariaDB
-- PHP Version: 8.1.12

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
START TRANSACTION;
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Database: `magento2`
--

-- --------------------------------------------------------

--
-- Table structure for table `master_data`
--

CREATE TABLE `master_data` (
  `id` int(32) NOT NULL,
  `unique_part_id` varchar(255) NOT NULL,
  `part_name` varchar(255) NOT NULL,
  `make` varchar(255) DEFAULT NULL,
  `model` varchar(255) DEFAULT NULL,
  `vehicle_type` text DEFAULT NULL,
  `part_category` text DEFAULT NULL,
  `size` text DEFAULT NULL,
  `position_1` text DEFAULT NULL,
  `position_2` text DEFAULT NULL,
  `height_cm` int(10) DEFAULT NULL,
  `length_cm` int(10) DEFAULT NULL,
  `width_cm` int(10) DEFAULT NULL,
  `weight_kg` int(10) DEFAULT NULL,
  `hsn_code` text DEFAULT NULL,
  `description` text DEFAULT NULL,
  `shipping_information` varchar(255) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

--
-- Dumping data for table `master_data`
--

INSERT INTO `master_data` (`id`, `unique_part_id`, `part_name`, `make`, `model`, `vehicle_type`, `part_category`, `size`, `position_1`, `position_2`, `height_cm`, `length_cm`, `width_cm`, `weight_kg`, `hsn_code`, `description`, `shipping_information`) VALUES
(352, 'FACAC01BM06', 'AB Compressor', 'BMW', '5-Series', '4W', 'Air Conditioning', NULL, NULL, NULL, 14, 19, 14, 6, '84149040', 'The product is a pre-owned or pre-used spare part collected form CERO Recycling centres. It has passed quality inspection at CERO. The pictures shown of the product are the actual images of the product.\nThe product comes with CERO Spares Guarantee. If the product has any genuine fitment issues / defects please inform us within 7 days from date of delivery and we will replace the same else refund the order. ', 'The product will be shipped via logistics partners appointed by CERO. We aim for quick dispatch and delivery. '),
(353, 'FACAL01BM06', 'Condensor', 'BMW', '5-Series', '4W', 'Air Conditioning', NULL, NULL, NULL, 65, 46, 46, 5, '84041000', 'The product is a pre-owned or pre-used spare part collected form CERO Recycling centres. It has passed quality inspection at CERO. The pictures shown of the product are the actual images of the product.\nThe product comes with CERO Spares Guarantee. If the product has any genuine fitment issues / defects please inform us within 7 days from date of delivery and we will replace the same else refund the order. ', 'The product will be shipped via logistics partners appointed by CERO. We aim for quick dispatch and delivery. '),
(354, 'FACAL03BM06', 'Cooling Coil', 'BMW', '5-Series', '4W', 'Air Conditioning', NULL, NULL, NULL, 61, 52, 98, 1, '84181010', 'The product is a pre-owned or pre-used spare part collected form CERO Recycling centres. It has passed quality inspection at CERO. The pictures shown of the product are the actual images of the product.\nThe product comes with CERO Spares Guarantee. If the product has any genuine fitment issues / defects please inform us within 7 days from date of delivery and we will replace the same else refund the order. ', 'The product will be shipped via logistics partners appointed by CERO. We aim for quick dispatch and delivery. '),
(355, 'FACAL04BM06', 'Radiator', 'BMW', '5-Series', '4W', 'Engine and Transmission', NULL, NULL, NULL, 65, 46, 46, 6, '87087000', 'The product is a pre-owned or pre-used spare part collected form CERO Recycling centres. It has passed quality inspection at CERO. The pictures shown of the product are the actual images of the product.\nThe product comes with CERO Spares Guarantee. If the product has any genuine fitment issues / defects please inform us within 7 days from date of delivery and we will replace the same else refund the order. ', 'The product will be shipped via logistics partners appointed by CERO. We aim for quick dispatch and delivery. '),
(356, 'FACAL05BM06', 'Heater core', 'BMW', '5-Series', '4W', 'Air Conditioning', NULL, NULL, NULL, 61, 52, 98, 3, '87087000', 'The product is a pre-owned or pre-used spare part collected form CERO Recycling centres. It has passed quality inspection at CERO. The pictures shown of the product are the actual images of the product.\nThe product comes with CERO Spares Guarantee. If the product has any genuine fitment issues / defects please inform us within 7 days from date of delivery and we will replace the same else refund the order. ', 'The product will be shipped via logistics partners appointed by CERO. We aim for quick dispatch and delivery. '),
(357, 'FACAT01BM06', 'Alternator', 'BMW', '5-Series', '4W', 'Electrical', NULL, NULL, NULL, 14, 13, 13, 5, '85112010', 'The product is a pre-owned or pre-used spare part collected form CERO Recycling centres. It has passed quality inspection at CERO. The pictures shown of the product are the actual images of the product.\nThe product comes with CERO Spares Guarantee. If the product has any genuine fitment issues / defects please inform us within 7 days from date of delivery and we will replace the same else refund the order. ', 'The product will be shipped via logistics partners appointed by CERO. We aim for quick dispatch and delivery. '),
(358, 'FACDR01BM06', 'Door', 'BMW', '5-Series', '4W', 'Body Part', NULL, 'Left', 'Front', 18, 112, 123, 34, '87087000', 'The product is a pre-owned or pre-used spare part collected form CERO Recycling centres. It has passed quality inspection at CERO. The pictures shown of the product are the actual images of the product.\nThe product comes with CERO Spares Guarantee. If the product has any genuine fitment issues / defects please inform us within 7 days from date of delivery and we will replace the same else refund the order. ', 'The product will be shipped via logistics partners appointed by CERO. We aim for quick dispatch and delivery. '),
(359, 'FACDR02BM06', 'Door', 'BMW', '5-Series', '4W', 'Body Part', NULL, 'Right', 'Front', 18, 112, 123, 34, '87087000', 'The product is a pre-owned or pre-used spare part collected form CERO Recycling centres. It has passed quality inspection at CERO. The pictures shown of the product are the actual images of the product.\nThe product comes with CERO Spares Guarantee. If the product has any genuine fitment issues / defects please inform us within 7 days from date of delivery and we will replace the same else refund the order. ', 'The product will be shipped via logistics partners appointed by CERO. We aim for quick dispatch and delivery. '),
(360, 'FACDR03BM06', 'Door', 'BMW', '5-Series', '4W', 'Body Part', NULL, 'Left', 'Rear', 20, 112, 101, 29, '87087000', 'The product is a pre-owned or pre-used spare part collected form CERO Recycling centres. It has passed quality inspection at CERO. The pictures shown of the product are the actual images of the product.\nThe product comes with CERO Spares Guarantee. If the product has any genuine fitment issues / defects please inform us within 7 days from date of delivery and we will replace the same else refund the order. ', 'The product will be shipped via logistics partners appointed by CERO. We aim for quick dispatch and delivery. '),
(361, 'FACDR04BM06', 'Door', 'BMW', '5-Series', '4W', 'Body Part', NULL, 'Right', 'Rear', 20, 112, 101, 29, '87087000', 'The product is a pre-owned or pre-used spare part collected form CERO Recycling centres. It has passed quality inspection at CERO. The pictures shown of the product are the actual images of the product.\nThe product comes with CERO Spares Guarantee. If the product has any genuine fitment issues / defects please inform us within 7 days from date of delivery and we will replace the same else refund the order. ', 'The product will be shipped via logistics partners appointed by CERO. We aim for quick dispatch and delivery. '),
(362, 'FACDR05BM06', 'Bonnet / Hood', 'BMW', '5-Series', '4W', 'Body Part', NULL, NULL, NULL, 8, 147, 166, 13, '87087000', 'The product is a pre-owned or pre-used spare part collected form CERO Recycling centres. It has passed quality inspection at CERO. The pictures shown of the product are the actual images of the product.\nThe product comes with CERO Spares Guarantee. If the product has any genuine fitment issues / defects please inform us within 7 days from date of delivery and we will replace the same else refund the order. ', 'The product will be shipped via logistics partners appointed by CERO. We aim for quick dispatch and delivery. '),
(363, 'FACDR06BM06', 'Boot / Trunk', 'BMW', '5-Series', '4W', 'Body Part', NULL, NULL, NULL, 51, 147, 47, 19, '87087000', 'The product is a pre-owned or pre-used spare part collected form CERO Recycling centres. It has passed quality inspection at CERO. The pictures shown of the product are the actual images of the product.\nThe product comes with CERO Spares Guarantee. If the product has any genuine fitment issues / defects please inform us within 7 days from date of delivery and we will replace the same else refund the order. ', 'The product will be shipped via logistics partners appointed by CERO. We aim for quick dispatch and delivery. '),
(364, 'FACEL01BM06', 'AC Blower Fan', 'BMW', '5-Series', '4W', 'Air Conditioning', NULL, NULL, NULL, 61, 52, 98, 2, '84149040', 'The product is a pre-owned or pre-used spare part collected form CERO Recycling centres. It has passed quality inspection at CERO. The pictures shown of the product are the actual images of the product.\nThe product comes with CERO Spares Guarantee. If the product has any genuine fitment issues / defects please inform us within 7 days from date of delivery and we will replace the same else refund the order. ', 'The product will be shipped via logistics partners appointed by CERO. We aim for quick dispatch and delivery. '),
(365, 'FACEL03BM06', 'Starter', 'BMW', '5-Series', '4W', 'Electrical', NULL, NULL, NULL, 12, 11, 11, 4, '85112010', 'The product is a pre-owned or pre-used spare part collected form CERO Recycling centres. It has passed quality inspection at CERO. The pictures shown of the product are the actual images of the product.\nThe product comes with CERO Spares Guarantee. If the product has any genuine fitment issues / defects please inform us within 7 days from date of delivery and we will replace the same else refund the order. ', 'The product will be shipped via logistics partners appointed by CERO. We aim for quick dispatch and delivery. '),
(366, 'FACEL05BM06', 'Radiator fan', 'BMW', '5-Series', '4W', 'Engine and Transmission', NULL, NULL, NULL, 63, 50, 50, 3, '87087000', 'The product is a pre-owned or pre-used spare part collected form CERO Recycling centres. It has passed quality inspection at CERO. The pictures shown of the product are the actual images of the product.\nThe product comes with CERO Spares Guarantee. If the product has any genuine fitment issues / defects please inform us within 7 days from date of delivery and we will replace the same else refund the order. ', 'The product will be shipped via logistics partners appointed by CERO. We aim for quick dispatch and delivery. '),
(367, 'FACEW04BM06', 'AC Control Panel', 'BMW', '5-Series', '4W', 'Air Conditioning', NULL, NULL, NULL, 29, 15, 14, 1, '87087000', 'The product is a pre-owned or pre-used spare part collected form CERO Recycling centres. It has passed quality inspection at CERO. The pictures shown of the product are the actual images of the product.\nThe product comes with CERO Spares Guarantee. If the product has any genuine fitment issues / defects please inform us within 7 days from date of delivery and we will replace the same else refund the order. ', 'The product will be shipped via logistics partners appointed by CERO. We aim for quick dispatch and delivery. '),
(368, 'FACEW08BM06', 'Speedometer', 'BMW', '5-Series', '4W', 'Cabin Interior', NULL, NULL, NULL, 32, 17, 14, 1, '85112010', 'The product is a pre-owned or pre-used spare part collected form CERO Recycling centres. It has passed quality inspection at CERO. The pictures shown of the product are the actual images of the product.\nThe product comes with CERO Spares Guarantee. If the product has any genuine fitment issues / defects please inform us within 7 days from date of delivery and we will replace the same else refund the order. ', 'The product will be shipped via logistics partners appointed by CERO. We aim for quick dispatch and delivery. '),
(369, 'FACEW09BM06', 'Horn set (Pair)', 'BMW', '5-Series', '4W', 'Electrical', NULL, NULL, NULL, 9, 9, 4, 0, '85112010', 'The product is a pre-owned or pre-used spare part collected form CERO Recycling centres. It has passed quality inspection at CERO. The pictures shown of the product are the actual images of the product.\nThe product comes with CERO Spares Guarantee. If the product has any genuine fitment issues / defects please inform us within 7 days from date of delivery and we will replace the same else refund the order. ', 'The product will be shipped via logistics partners appointed by CERO. We aim for quick dispatch and delivery. '),
(370, 'FACIN01BM06', 'Driver Seat', 'BMW', '5-Series', '4W', 'Seat', NULL, NULL, NULL, 48, 124, 56, 27, '94012000', 'The product is a pre-owned or pre-used spare part collected form CERO Recycling centres. It has passed quality inspection at CERO. The pictures shown of the product are the actual images of the product.\nThe product comes with CERO Spares Guarantee. If the product has any genuine fitment issues / defects please inform us within 7 days from date of delivery and we will replace the same else refund the order. ', 'The product will be shipped via logistics partners appointed by CERO. We aim for quick dispatch and delivery. '),
(371, 'FACIN02BM06', 'Passenger Seat', 'BMW', '5-Series', '4W', 'Seat', NULL, NULL, NULL, 48, 124, 56, 27, '94012000', 'The product is a pre-owned or pre-used spare part collected form CERO Recycling centres. It has passed quality inspection at CERO. The pictures shown of the product are the actual images of the product.\nThe product comes with CERO Spares Guarantee. If the product has any genuine fitment issues / defects please inform us within 7 days from date of delivery and we will replace the same else refund the order. ', 'The product will be shipped via logistics partners appointed by CERO. We aim for quick dispatch and delivery. '),
(372, 'FACPS02BM06', 'Head Light', 'BMW', '5-Series', '4W', 'Lights', NULL, 'Left', NULL, 31, 65, 28, 4, '85121000', 'The product is a pre-owned or pre-used spare part collected form CERO Recycling centres. It has passed quality inspection at CERO. The pictures shown of the product are the actual images of the product.\nThe product comes with CERO Spares Guarantee. If the product has any genuine fitment issues / defects please inform us within 7 days from date of delivery and we will replace the same else refund the order. ', 'The product will be shipped via logistics partners appointed by CERO. We aim for quick dispatch and delivery. '),
(373, 'FACPS03BM06', 'Head Light', 'BMW', '5-Series', '4W', 'Lights', NULL, 'Right', NULL, 31, 65, 28, 4, '85121000', 'The product is a pre-owned or pre-used spare part collected form CERO Recycling centres. It has passed quality inspection at CERO. The pictures shown of the product are the actual images of the product.\nThe product comes with CERO Spares Guarantee. If the product has any genuine fitment issues / defects please inform us within 7 days from date of delivery and we will replace the same else refund the order. ', 'The product will be shipped via logistics partners appointed by CERO. We aim for quick dispatch and delivery. '),
(374, 'FACPS04BM06', 'Tail Light', 'BMW', '5-Series', '4W', 'Lights', NULL, 'Left', NULL, 19, 54, 10, 2, '85121000', 'The product is a pre-owned or pre-used spare part collected form CERO Recycling centres. It has passed quality inspection at CERO. The pictures shown of the product are the actual images of the product.\nThe product comes with CERO Spares Guarantee. If the product has any genuine fitment issues / defects please inform us within 7 days from date of delivery and we will replace the same else refund the order. ', 'The product will be shipped via logistics partners appointed by CERO. We aim for quick dispatch and delivery. '),
(375, 'FACPS05BM06', 'Tail Light', 'BMW', '5-Series', '4W', 'Lights', NULL, 'Right', NULL, 19, 54, 10, 2, '85121000', 'The product is a pre-owned or pre-used spare part collected form CERO Recycling centres. It has passed quality inspection at CERO. The pictures shown of the product are the actual images of the product.\nThe product comes with CERO Spares Guarantee. If the product has any genuine fitment issues / defects please inform us within 7 days from date of delivery and we will replace the same else refund the order. ', 'The product will be shipped via logistics partners appointed by CERO. We aim for quick dispatch and delivery. '),
(376, 'FACPS06BM06', 'Bumper', 'BMW', '5-Series', '4W', 'Body Part', NULL, NULL, 'Front', 50, 162, 41, 8, '87087000', 'The product is a pre-owned or pre-used spare part collected form CERO Recycling centres. It has passed quality inspection at CERO. The pictures shown of the product are the actual images of the product.\nThe product comes with CERO Spares Guarantee. If the product has any genuine fitment issues / defects please inform us within 7 days from date of delivery and we will replace the same else refund the order. ', 'The product will be shipped via logistics partners appointed by CERO. We aim for quick dispatch and delivery. '),
(377, 'FACPS12BM06', 'Dashboard without Airbag', 'BMW', '5-Series', '4W', 'Cabin Interior', NULL, NULL, NULL, 35, 144, 51, 17, '87087000', 'The product is a pre-owned or pre-used spare part collected form CERO Recycling centres. It has passed quality inspection at CERO. The pictures shown of the product are the actual images of the product.\nThe product comes with CERO Spares Guarantee. If the product has any genuine fitment issues / defects please inform us within 7 days from date of delivery and we will replace the same else refund the order. ', 'The product will be shipped via logistics partners appointed by CERO. We aim for quick dispatch and delivery. '),
(378, 'FACSS03BM06', 'Engine Holding Lower Frame or Cross Member', 'BMW', '5-Series', '4W', 'Engine and Transmission', NULL, NULL, NULL, 51, 149, 82, 23, '87087000', 'The product is a pre-owned or pre-used spare part collected form CERO Recycling centres. It has passed quality inspection at CERO. The pictures shown of the product are the actual images of the product.\nThe product comes with CERO Spares Guarantee. If the product has any genuine fitment issues / defects please inform us within 7 days from date of delivery and we will replace the same else refund the order. ', 'The product will be shipped via logistics partners appointed by CERO. We aim for quick dispatch and delivery. '),
(379, 'FACSS05BM06', 'Steering rack Assy. (H)', 'BMW', '5-Series', '4W', 'Steering', NULL, NULL, NULL, 14, 141, 15, 13, '87087000', 'The product is a pre-owned or pre-used spare part collected form CERO Recycling centres. It has passed quality inspection at CERO. The pictures shown of the product are the actual images of the product.\nThe product comes with CERO Spares Guarantee. If the product has any genuine fitment issues / defects please inform us within 7 days from date of delivery and we will replace the same else refund the order. ', 'The product will be shipped via logistics partners appointed by CERO. We aim for quick dispatch and delivery. '),
(380, 'FACSS08BM06', 'Power Steering Column', 'BMW', '5-Series', '4W', 'Steering', NULL, NULL, NULL, 65, 39, 39, 11, '87087000', 'The product is a pre-owned or pre-used spare part collected form CERO Recycling centres. It has passed quality inspection at CERO. The pictures shown of the product are the actual images of the product.\nThe product comes with CERO Spares Guarantee. If the product has any genuine fitment issues / defects please inform us within 7 days from date of delivery and we will replace the same else refund the order. ', 'The product will be shipped via logistics partners appointed by CERO. We aim for quick dispatch and delivery. '),
(381, 'FACSS09BM06', 'Car Jack - Manual', 'BMW', '5-Series', '4W', 'Accessories', NULL, NULL, NULL, 36, 7, 5, 3, '87087000', 'The product is a pre-owned or pre-used spare part collected form CERO Recycling centres. It has passed quality inspection at CERO. The pictures shown of the product are the actual images of the product.\nThe product comes with CERO Spares Guarantee. If the product has any genuine fitment issues / defects please inform us within 7 days from date of delivery and we will replace the same else refund the order. ', 'The product will be shipped via logistics partners appointed by CERO. We aim for quick dispatch and delivery. '),
(382, 'FACSS15BM06', 'Shocker+Spring', 'BMW', '5-Series', '4W', 'Suspension', NULL, 'Left', 'Front', 64, 13, 13, 5, '87087000', 'The product is a pre-owned or pre-used spare part collected form CERO Recycling centres. It has passed quality inspection at CERO. The pictures shown of the product are the actual images of the product.\nThe product comes with CERO Spares Guarantee. If the product has any genuine fitment issues / defects please inform us within 7 days from date of delivery and we will replace the same else refund the order. ', 'The product will be shipped via logistics partners appointed by CERO. We aim for quick dispatch and delivery. '),
(383, 'FACSS16BM06', 'Shocker+Spring', 'BMW', '5-Series', '4W', 'Suspension', NULL, 'Right', 'Front', 64, 13, 13, 5, '87087000', 'The product is a pre-owned or pre-used spare part collected form CERO Recycling centres. It has passed quality inspection at CERO. The pictures shown of the product are the actual images of the product.\nThe product comes with CERO Spares Guarantee. If the product has any genuine fitment issues / defects please inform us within 7 days from date of delivery and we will replace the same else refund the order. ', 'The product will be shipped via logistics partners appointed by CERO. We aim for quick dispatch and delivery. '),
(384, 'FACSS17BM06', 'Shocker', 'BMW', '5-Series', '4W', 'Suspension', NULL, 'Left', 'Rear', 63, 15, 15, 5, '87087000', 'The product is a pre-owned or pre-used spare part collected form CERO Recycling centres. It has passed quality inspection at CERO. The pictures shown of the product are the actual images of the product.\nThe product comes with CERO Spares Guarantee. If the product has any genuine fitment issues / defects please inform us within 7 days from date of delivery and we will replace the same else refund the order. ', 'The product will be shipped via logistics partners appointed by CERO. We aim for quick dispatch and delivery. '),
(385, 'FACSS18BM06', 'Shocker', 'BMW', '5-Series', '4W', 'Suspension', NULL, 'Right', 'Rear', 63, 15, 15, 5, '87087000', 'The product is a pre-owned or pre-used spare part collected form CERO Recycling centres. It has passed quality inspection at CERO. The pictures shown of the product are the actual images of the product.\nThe product comes with CERO Spares Guarantee. If the product has any genuine fitment issues / defects please inform us within 7 days from date of delivery and we will replace the same else refund the order. ', 'The product will be shipped via logistics partners appointed by CERO. We aim for quick dispatch and delivery. '),
(386, 'FACEL02BM06', 'Wiper Motor ', 'BMW', '5-Series', '4W', 'Electrical', NULL, NULL, NULL, 82, 13, 13, 3, '87087000', 'The product is a pre-owned or pre-used spare part collected form CERO Recycling centres. It has passed quality inspection at CERO. The pictures shown of the product are the actual images of the product.\nThe product comes with CERO Spares Guarantee. If the product has any genuine fitment issues / defects please inform us within 7 days from date of delivery and we will replace the same else refund the order. ', 'The product will be shipped via logistics partners appointed by CERO. We aim for quick dispatch and delivery. '),
(387, 'FACEW02BM06', 'Fuses (BOX)', 'BMW', '5-Series', '4W', 'Electrical', NULL, NULL, NULL, 45, 12, 12, 1, '87087000', 'The product is a pre-owned or pre-used spare part collected form CERO Recycling centres. It has passed quality inspection at CERO. The pictures shown of the product are the actual images of the product.\nThe product comes with CERO Spares Guarantee. If the product has any genuine fitment issues / defects please inform us within 7 days from date of delivery and we will replace the same else refund the order. ', 'The product will be shipped via logistics partners appointed by CERO. We aim for quick dispatch and delivery. '),
(388, 'FACIN03BM06', 'Rear Seat', 'BMW', '5-Series', '4W', 'Seat', NULL, NULL, NULL, 72, 161, 64, 41, '94012000', 'The product is a pre-owned or pre-used spare part collected form CERO Recycling centres. It has passed quality inspection at CERO. The pictures shown of the product are the actual images of the product.\nThe product comes with CERO Spares Guarantee. If the product has any genuine fitment issues / defects please inform us within 7 days from date of delivery and we will replace the same else refund the order. ', 'The product will be shipped via logistics partners appointed by CERO. We aim for quick dispatch and delivery. '),
(389, 'FACPS07BM06', 'Bumper', 'BMW', '5-Series', '4W', 'Body Part', NULL, NULL, 'Rear', 52, 201, 72, 7, '87087000', 'The product is a pre-owned or pre-used spare part collected form CERO Recycling centres. It has passed quality inspection at CERO. The pictures shown of the product are the actual images of the product.\nThe product comes with CERO Spares Guarantee. If the product has any genuine fitment issues / defects please inform us within 7 days from date of delivery and we will replace the same else refund the order. ', 'The product will be shipped via logistics partners appointed by CERO. We aim for quick dispatch and delivery. '),
(390, 'FACPS13BM06', 'Fuel pump', 'BMW', '5-Series', '4W', 'Fuel System', NULL, NULL, NULL, 11, 11, 46, 1, '87087000', 'The product is a pre-owned or pre-used spare part collected form CERO Recycling centres. It has passed quality inspection at CERO. The pictures shown of the product are the actual images of the product.\nThe product comes with CERO Spares Guarantee. If the product has any genuine fitment issues / defects please inform us within 7 days from date of delivery and we will replace the same else refund the order. ', 'The product will be shipped via logistics partners appointed by CERO. We aim for quick dispatch and delivery. '),
(391, 'FACSS01BM06', 'Fender', 'BMW', '5-Series', '4W', 'Body Part', NULL, 'Left', NULL, 8, 131, 69, 2, '87087000', 'The product is a pre-owned or pre-used spare part collected form CERO Recycling centres. It has passed quality inspection at CERO. The pictures shown of the product are the actual images of the product.\nThe product comes with CERO Spares Guarantee. If the product has any genuine fitment issues / defects please inform us within 7 days from date of delivery and we will replace the same else refund the order. ', 'The product will be shipped via logistics partners appointed by CERO. We aim for quick dispatch and delivery. '),
(392, 'FACSS02BM06', 'Fender', 'BMW', '5-Series', '4W', 'Body Part', NULL, 'Right', NULL, 8, 131, 69, 2, '87087000', 'The product is a pre-owned or pre-used spare part collected form CERO Recycling centres. It has passed quality inspection at CERO. The pictures shown of the product are the actual images of the product.\nThe product comes with CERO Spares Guarantee. If the product has any genuine fitment issues / defects please inform us within 7 days from date of delivery and we will replace the same else refund the order. ', 'The product will be shipped via logistics partners appointed by CERO. We aim for quick dispatch and delivery. '),
(393, 'FACSS04BM06', 'Steering Rack Assy. (N)', 'BMW', '5-Series', '4W', 'Steering', NULL, NULL, NULL, 14, 141, 15, 13, '87087000', 'The product is a pre-owned or pre-used spare part collected form CERO Recycling centres. It has passed quality inspection at CERO. The pictures shown of the product are the actual images of the product.\nThe product comes with CERO Spares Guarantee. If the product has any genuine fitment issues / defects please inform us within 7 days from date of delivery and we will replace the same else refund the order. ', 'The product will be shipped via logistics partners appointed by CERO. We aim for quick dispatch and delivery. '),
(394, 'FACSS07BM06', 'Steering column Assy (N)', 'BMW', '5-Series', '4W', 'Steering', NULL, NULL, NULL, 65, 39, 39, 11, '87087000', 'The product is a pre-owned or pre-used spare part collected form CERO Recycling centres. It has passed quality inspection at CERO. The pictures shown of the product are the actual images of the product.\nThe product comes with CERO Spares Guarantee. If the product has any genuine fitment issues / defects please inform us within 7 days from date of delivery and we will replace the same else refund the order. ', 'The product will be shipped via logistics partners appointed by CERO. We aim for quick dispatch and delivery. '),
(395, 'FACSS11BM06', 'Axle', 'BMW', '5-Series', '4W', 'Axles', NULL, NULL, 'Rear', 39, 149, 39, 110, '87087000', 'The product is a pre-owned or pre-used spare part collected form CERO Recycling centres. It has passed quality inspection at CERO. The pictures shown of the product are the actual images of the product.\nThe product comes with CERO Spares Guarantee. If the product has any genuine fitment issues / defects please inform us within 7 days from date of delivery and we will replace the same else refund the order. ', 'The product will be shipped via logistics partners appointed by CERO. We aim for quick dispatch and delivery. '),
(396, 'FACSS12BM06', 'Axle', 'BMW', '5-Series', '4W', 'Axles', NULL, 'Left', 'Front', 14, 76, 14, 5, '87087000', 'The product is a pre-owned or pre-used spare part collected form CERO Recycling centres. It has passed quality inspection at CERO. The pictures shown of the product are the actual images of the product.\nThe product comes with CERO Spares Guarantee. If the product has any genuine fitment issues / defects please inform us within 7 days from date of delivery and we will replace the same else refund the order. ', 'The product will be shipped via logistics partners appointed by CERO. We aim for quick dispatch and delivery. '),
(397, 'FACSS13BM06', 'Axle', 'BMW', '5-Series', '4W', 'Axles', NULL, 'Right', 'Front', 14, 78, 14, 6, '87087000', 'The product is a pre-owned or pre-used spare part collected form CERO Recycling centres. It has passed quality inspection at CERO. The pictures shown of the product are the actual images of the product.\nThe product comes with CERO Spares Guarantee. If the product has any genuine fitment issues / defects please inform us within 7 days from date of delivery and we will replace the same else refund the order. ', 'The product will be shipped via logistics partners appointed by CERO. We aim for quick dispatch and delivery. '),
(398, 'FACSS21BM06', 'Engine mounting (N1)', 'BMW', '5-Series', '4W', 'Engine and Transmission', NULL, NULL, NULL, 11, 11, 9, 1, '87087000', 'The product is a pre-owned or pre-used spare part collected form CERO Recycling centres. It has passed quality inspection at CERO. The pictures shown of the product are the actual images of the product.\nThe product comes with CERO Spares Guarantee. If the product has any genuine fitment issues / defects please inform us within 7 days from date of delivery and we will replace the same else refund the order. ', 'The product will be shipped via logistics partners appointed by CERO. We aim for quick dispatch and delivery. '),
(399, 'FACSS22BM06', 'Engine mounting (N2)', 'BMW', '5-Series', '4W', 'Engine and Transmission', NULL, NULL, NULL, 11, 11, 9, 1, '87087000', 'The product is a pre-owned or pre-used spare part collected form CERO Recycling centres. It has passed quality inspection at CERO. The pictures shown of the product are the actual images of the product.\nThe product comes with CERO Spares Guarantee. If the product has any genuine fitment issues / defects please inform us within 7 days from date of delivery and we will replace the same else refund the order. ', 'The product will be shipped via logistics partners appointed by CERO. We aim for quick dispatch and delivery. '),
(400, 'FACSS24BM06', 'Front End Panel / Tie (Complete)', 'BMW', '5-Series', '4W', 'Body Part', NULL, NULL, NULL, 38, 127, 22, 8, '87087000', 'The product is a pre-owned or pre-used spare part collected form CERO Recycling centres. It has passed quality inspection at CERO. The pictures shown of the product are the actual images of the product.\nThe product comes with CERO Spares Guarantee. If the product has any genuine fitment issues / defects please inform us within 7 days from date of delivery and we will replace the same else refund the order. ', 'The product will be shipped via logistics partners appointed by CERO. We aim for quick dispatch and delivery. '),
(401, 'FACSS29BM06', 'Propeller Shaft', 'BMW', '5-Series', '4W', 'Engine and Transmission', NULL, NULL, 'Front', 164, 11, 11, 9, '87087000', 'The product is a pre-owned or pre-used spare part collected form CERO Recycling centres. It has passed quality inspection at CERO. The pictures shown of the product are the actual images of the product.\nThe product comes with CERO Spares Guarantee. If the product has any genuine fitment issues / defects please inform us within 7 days from date of delivery and we will replace the same else refund the order. ', 'The product will be shipped via logistics partners appointed by CERO. We aim for quick dispatch and delivery. '),
(402, 'FACSS32BM06', 'Fuel Tank (Steel)', 'BMW', '5-Series', '4W', 'Fuel System', NULL, NULL, NULL, 36, 94, 38, 11, '87087000', 'The product is a pre-owned or pre-used spare part collected form CERO Recycling centres. It has passed quality inspection at CERO. The pictures shown of the product are the actual images of the product.\nThe product comes with CERO Spares Guarantee. If the product has any genuine fitment issues / defects please inform us within 7 days from date of delivery and we will replace the same else refund the order. ', 'The product will be shipped via logistics partners appointed by CERO. We aim for quick dispatch and delivery. '),
(403, 'FACAC01MA02', 'AC Compressor', 'Maruti Suzuki', '800 std.', '4W', 'Air Conditioning', NULL, NULL, NULL, 13, 21, 16, 4, '84149040', 'The product is a pre-owned or pre-used spare part collected form CERO Recycling centres. It has passed quality inspection at CERO. The pictures shown of the product are the actual images of the product.\nThe product comes with CERO Spares Guarantee. If the product has any genuine fitment issues / defects please inform us within 7 days from date of delivery and we will replace the same else refund the order. ', 'The product will be shipped via logistics partners appointed by CERO. We aim for quick dispatch and delivery. '),
(404, 'FACAL04MA02', 'Radiator', 'Maruti Suzuki', '800 std.', '4W', 'Engine and Transmission', NULL, NULL, NULL, 65, 18, 50, 3, '87087000', 'The product is a pre-owned or pre-used spare part collected form CERO Recycling centres. It has passed quality inspection at CERO. The pictures shown of the product are the actual images of the product.\nThe product comes with CERO Spares Guarantee. If the product has any genuine fitment issues / defects please inform us within 7 days from date of delivery and we will replace the same else refund the order. ', 'The product will be shipped via logistics partners appointed by CERO. We aim for quick dispatch and delivery. '),
(405, 'FACAT01MA02', 'Alternator', 'Maruti Suzuki', '800 std.', '4W', 'Electrical', NULL, NULL, NULL, 19, 20, 17, 4, '85112010', 'The product is a pre-owned or pre-used spare part collected form CERO Recycling centres. It has passed quality inspection at CERO. The pictures shown of the product are the actual images of the product.\nThe product comes with CERO Spares Guarantee. If the product has any genuine fitment issues / defects please inform us within 7 days from date of delivery and we will replace the same else refund the order. ', 'The product will be shipped via logistics partners appointed by CERO. We aim for quick dispatch and delivery. '),
(406, 'FACDR01MA02', 'Door', 'Maruti Suzuki', '800 std.', '4W', 'Body Part', NULL, 'Left', 'Front', 112, 26, 117, 18, '87087000', 'The product is a pre-owned or pre-used spare part collected form CERO Recycling centres. It has passed quality inspection at CERO. The pictures shown of the product are the actual images of the product.\nThe product comes with CERO Spares Guarantee. If the product has any genuine fitment issues / defects please inform us within 7 days from date of delivery and we will replace the same else refund the order. ', 'The product will be shipped via logistics partners appointed by CERO. We aim for quick dispatch and delivery. '),
(407, 'FACDR02MA02', 'Door', 'Maruti Suzuki', '800 std.', '4W', 'Body Part', NULL, 'Right', 'Front', 131, 23, 125, 18, '87087000', 'The product is a pre-owned or pre-used spare part collected form CERO Recycling centres. It has passed quality inspection at CERO. The pictures shown of the product are the actual images of the product.\nThe product comes with CERO Spares Guarantee. If the product has any genuine fitment issues / defects please inform us within 7 days from date of delivery and we will replace the same else refund the order. ', 'The product will be shipped via logistics partners appointed by CERO. We aim for quick dispatch and delivery. '),
(408, 'FACDR03MA02', 'Door', 'Maruti Suzuki', '800 std.', '4W', 'Body Part', NULL, 'Left', 'Rear', 117, 24, 115, 16, '87087000', 'The product is a pre-owned or pre-used spare part collected form CERO Recycling centres. It has passed quality inspection at CERO. The pictures shown of the product are the actual images of the product.\nThe product comes with CERO Spares Guarantee. If the product has any genuine fitment issues / defects please inform us within 7 days from date of delivery and we will replace the same else refund the order. ', 'The product will be shipped via logistics partners appointed by CERO. We aim for quick dispatch and delivery. '),
(409, 'FACDR04MA02', 'Door', 'Maruti Suzuki', '800 std.', '4W', 'Body Part', NULL, 'Right', 'Rear', 129, 25, 118, 16, '87087000', 'The product is a pre-owned or pre-used spare part collected form CERO Recycling centres. It has passed quality inspection at CERO. The pictures shown of the product are the actual images of the product.\nThe product comes with CERO Spares Guarantee. If the product has any genuine fitment issues / defects please inform us within 7 days from date of delivery and we will replace the same else refund the order. ', 'The product will be shipped via logistics partners appointed by CERO. We aim for quick dispatch and delivery. '),
(410, 'FACDR05MA02', 'Bonnet / Hood', 'Maruti Suzuki', '800 std.', '4W', 'Body Part', NULL, NULL, NULL, 76, 120, 11, 9, '87087000', 'The product is a pre-owned or pre-used spare part collected form CERO Recycling centres. It has passed quality inspection at CERO. The pictures shown of the product are the actual images of the product.\nThe product comes with CERO Spares Guarantee. If the product has any genuine fitment issues / defects please inform us within 7 days from date of delivery and we will replace the same else refund the order. ', 'The product will be shipped via logistics partners appointed by CERO. We aim for quick dispatch and delivery. '),
(411, 'FACDR06MA02', 'Boot / Trunk', 'Maruti Suzuki', '800 std.', '4W', 'Body Part', NULL, NULL, NULL, 95, 132, 27, 14, '87087000', 'The product is a pre-owned or pre-used spare part collected form CERO Recycling centres. It has passed quality inspection at CERO. The pictures shown of the product are the actual images of the product.\nThe product comes with CERO Spares Guarantee. If the product has any genuine fitment issues / defects please inform us within 7 days from date of delivery and we will replace the same else refund the order. ', 'The product will be shipped via logistics partners appointed by CERO. We aim for quick dispatch and delivery. '),
(412, 'FACEL02MA02', 'Wiper Motor ', 'Maruti Suzuki', '800 std.', '4W', 'Electrical', NULL, NULL, NULL, 27, 16, 10, 2, '87087000', 'The product is a pre-owned or pre-used spare part collected form CERO Recycling centres. It has passed quality inspection at CERO. The pictures shown of the product are the actual images of the product.\nThe product comes with CERO Spares Guarantee. If the product has any genuine fitment issues / defects please inform us within 7 days from date of delivery and we will replace the same else refund the order. ', 'The product will be shipped via logistics partners appointed by CERO. We aim for quick dispatch and delivery. '),
(413, 'FACEL03MA02', 'Starter', 'Maruti Suzuki', '800 std.', '4W', 'Electrical', NULL, NULL, NULL, 24, 12, 15, 3, '85112010', 'The product is a pre-owned or pre-used spare part collected form CERO Recycling centres. It has passed quality inspection at CERO. The pictures shown of the product are the actual images of the product.\nThe product comes with CERO Spares Guarantee. If the product has any genuine fitment issues / defects please inform us within 7 days from date of delivery and we will replace the same else refund the order. ', 'The product will be shipped via logistics partners appointed by CERO. We aim for quick dispatch and delivery. '),
(414, 'FACEL05MA02', 'Radiator fan', 'Maruti Suzuki', '800 std.', '4W', 'Engine and Transmission', NULL, NULL, NULL, 52, 20, 45, 1, '87087000', 'The product is a pre-owned or pre-used spare part collected form CERO Recycling centres. It has passed quality inspection at CERO. The pictures shown of the product are the actual images of the product.\nThe product comes with CERO Spares Guarantee. If the product has any genuine fitment issues / defects please inform us within 7 days from date of delivery and we will replace the same else refund the order. ', 'The product will be shipped via logistics partners appointed by CERO. We aim for quick dispatch and delivery. '),
(415, 'FACEW09MA02', 'Horn set (Pair)', 'Maruti Suzuki', '800 std.', '4W', 'Electrical', NULL, NULL, NULL, 12, 12, 12, 1, '85112010', 'The product is a pre-owned or pre-used spare part collected form CERO Recycling centres. It has passed quality inspection at CERO. The pictures shown of the product are the actual images of the product.\nThe product comes with CERO Spares Guarantee. If the product has any genuine fitment issues / defects please inform us within 7 days from date of delivery and we will replace the same else refund the order. ', 'The product will be shipped via logistics partners appointed by CERO. We aim for quick dispatch and delivery. '),
(416, 'FACIN01MA02', 'Driver Seat', 'Maruti Suzuki', '800 std.', '4W', 'Seat', NULL, NULL, NULL, 107, 66, 65, 11, '94012000', 'The product is a pre-owned or pre-used spare part collected form CERO Recycling centres. It has passed quality inspection at CERO. The pictures shown of the product are the actual images of the product.\nThe product comes with CERO Spares Guarantee. If the product has any genuine fitment issues / defects please inform us within 7 days from date of delivery and we will replace the same else refund the order. ', 'The product will be shipped via logistics partners appointed by CERO. We aim for quick dispatch and delivery. '),
(417, 'FACPS02MA02', 'Head Light', 'Maruti Suzuki', '800 std.', '4W', 'Lights', NULL, 'Left', NULL, 34, 25, 25, 1, '85121000', 'The product is a pre-owned or pre-used spare part collected form CERO Recycling centres. It has passed quality inspection at CERO. The pictures shown of the product are the actual images of the product.\nThe product comes with CERO Spares Guarantee. If the product has any genuine fitment issues / defects please inform us within 7 days from date of delivery and we will replace the same else refund the order. ', 'The product will be shipped via logistics partners appointed by CERO. We aim for quick dispatch and delivery. '),
(418, 'FACPS03MA02', 'Head Light', 'Maruti Suzuki', '800 std.', '4W', 'Lights', NULL, 'Right', NULL, 20, 40, 30, 1, '85121000', 'The product is a pre-owned or pre-used spare part collected form CERO Recycling centres. It has passed quality inspection at CERO. The pictures shown of the product are the actual images of the product.\nThe product comes with CERO Spares Guarantee. If the product has any genuine fitment issues / defects please inform us within 7 days from date of delivery and we will replace the same else refund the order. ', 'The product will be shipped via logistics partners appointed by CERO. We aim for quick dispatch and delivery. '),
(419, 'FACPS04MA02', 'Tail Light', 'Maruti Suzuki', '800 std.', '4W', 'Lights', NULL, 'Left', NULL, 13, 18, 26, 1, '85121000', 'The product is a pre-owned or pre-used spare part collected form CERO Recycling centres. It has passed quality inspection at CERO. The pictures shown of the product are the actual images of the product.\nThe product comes with CERO Spares Guarantee. If the product has any genuine fitment issues / defects please inform us within 7 days from date of delivery and we will replace the same else refund the order. ', 'The product will be shipped via logistics partners appointed by CERO. We aim for quick dispatch and delivery. '),
(420, 'FACPS05MA02', 'Tail Light', 'Maruti Suzuki', '800 std.', '4W', 'Lights', NULL, 'Right', NULL, 27, 18, 25, 1, '85121000', 'The product is a pre-owned or pre-used spare part collected form CERO Recycling centres. It has passed quality inspection at CERO. The pictures shown of the product are the actual images of the product.\nThe product comes with CERO Spares Guarantee. If the product has any genuine fitment issues / defects please inform us within 7 days from date of delivery and we will replace the same else refund the order. ', 'The product will be shipped via logistics partners appointed by CERO. We aim for quick dispatch and delivery. '),
(421, 'FACPS06MA02', 'Bumper', 'Maruti Suzuki', '800 std.', '4W', 'Body Part', NULL, NULL, 'Front', 150, 42, 35, 3, '87087000', 'The product is a pre-owned or pre-used spare part collected form CERO Recycling centres. It has passed quality inspection at CERO. The pictures shown of the product are the actual images of the product.\nThe product comes with CERO Spares Guarantee. If the product has any genuine fitment issues / defects please inform us within 7 days from date of delivery and we will replace the same else refund the order. ', 'The product will be shipped via logistics partners appointed by CERO. We aim for quick dispatch and delivery. '),
(422, 'FACPS12MA02', 'Dashboard without Airbag', 'Maruti Suzuki', '800 std.', '4W', 'Cabin Interior', NULL, NULL, NULL, 150, 55, 55, 4, '87087000', 'The product is a pre-owned or pre-used spare part collected form CERO Recycling centres. It has passed quality inspection at CERO. The pictures shown of the product are the actual images of the product.\nThe product comes with CERO Spares Guarantee. If the product has any genuine fitment issues / defects please inform us within 7 days from date of delivery and we will replace the same else refund the order. ', 'The product will be shipped via logistics partners appointed by CERO. We aim for quick dispatch and delivery. '),
(423, 'FACSS01MA02', 'Fender', 'Maruti Suzuki', '800 std.', '4W', 'Body Part', NULL, 'Left', NULL, 30, 27, 7, 2, '87087000', 'The product is a pre-owned or pre-used spare part collected form CERO Recycling centres. It has passed quality inspection at CERO. The pictures shown of the product are the actual images of the product.\nThe product comes with CERO Spares Guarantee. If the product has any genuine fitment issues / defects please inform us within 7 days from date of delivery and we will replace the same else refund the order. ', 'The product will be shipped via logistics partners appointed by CERO. We aim for quick dispatch and delivery. '),
(424, 'FACSS02MA02', 'Fender', 'Maruti Suzuki', '800 std.', '4W', 'Body Part', NULL, 'Right', NULL, 31, 29, 8, 2, '87087000', 'The product is a pre-owned or pre-used spare part collected form CERO Recycling centres. It has passed quality inspection at CERO. The pictures shown of the product are the actual images of the product.\nThe product comes with CERO Spares Guarantee. If the product has any genuine fitment issues / defects please inform us within 7 days from date of delivery and we will replace the same else refund the order. ', 'The product will be shipped via logistics partners appointed by CERO. We aim for quick dispatch and delivery. '),
(425, 'FACSS11MA02', 'Axle', 'Maruti Suzuki', '800 std.', '4W', 'Axles', NULL, NULL, 'Rear', 77, 150, 28, 19, '87087000', 'The product is a pre-owned or pre-used spare part collected form CERO Recycling centres. It has passed quality inspection at CERO. The pictures shown of the product are the actual images of the product.\nThe product comes with CERO Spares Guarantee. If the product has any genuine fitment issues / defects please inform us within 7 days from date of delivery and we will replace the same else refund the order. ', 'The product will be shipped via logistics partners appointed by CERO. We aim for quick dispatch and delivery. '),
(426, 'FACSS12MA02', 'Axle', 'Maruti Suzuki', '800 std.', '4W', 'Axles', NULL, 'Left', 'Front', 152, 30, 75, 3, '87087000', 'The product is a pre-owned or pre-used spare part collected form CERO Recycling centres. It has passed quality inspection at CERO. The pictures shown of the product are the actual images of the product.\nThe product comes with CERO Spares Guarantee. If the product has any genuine fitment issues / defects please inform us within 7 days from date of delivery and we will replace the same else refund the order. ', 'The product will be shipped via logistics partners appointed by CERO. We aim for quick dispatch and delivery. ');
INSERT INTO `master_data` (`id`, `unique_part_id`, `part_name`, `make`, `model`, `vehicle_type`, `part_category`, `size`, `position_1`, `position_2`, `height_cm`, `length_cm`, `width_cm`, `weight_kg`, `hsn_code`, `description`, `shipping_information`) VALUES
(427, 'FACSS13MA02', 'Axle', 'Maruti Suzuki', '800 std.', '4W', 'Axles', NULL, 'Right', 'Front', 6, 69, 6, 3, '87087000', 'The product is a pre-owned or pre-used spare part collected form CERO Recycling centres. It has passed quality inspection at CERO. The pictures shown of the product are the actual images of the product.\nThe product comes with CERO Spares Guarantee. If the product has any genuine fitment issues / defects please inform us within 7 days from date of delivery and we will replace the same else refund the order. ', 'The product will be shipped via logistics partners appointed by CERO. We aim for quick dispatch and delivery. '),
(428, 'FACSS15MA02', 'Shocker+Spring', 'Maruti Suzuki', '800 std.', '4W', 'Suspension', NULL, 'Left', 'Front', 63, 17, 17, 4, '87087000', 'The product is a pre-owned or pre-used spare part collected form CERO Recycling centres. It has passed quality inspection at CERO. The pictures shown of the product are the actual images of the product.\nThe product comes with CERO Spares Guarantee. If the product has any genuine fitment issues / defects please inform us within 7 days from date of delivery and we will replace the same else refund the order. ', 'The product will be shipped via logistics partners appointed by CERO. We aim for quick dispatch and delivery. '),
(429, 'FACSS16MA02', 'Shocker+Spring', 'Maruti Suzuki', '800 std.', '4W', 'Suspension', NULL, 'Right', 'Front', 63, 17, 17, 4, '87087000', 'The product is a pre-owned or pre-used spare part collected form CERO Recycling centres. It has passed quality inspection at CERO. The pictures shown of the product are the actual images of the product.\nThe product comes with CERO Spares Guarantee. If the product has any genuine fitment issues / defects please inform us within 7 days from date of delivery and we will replace the same else refund the order. ', 'The product will be shipped via logistics partners appointed by CERO. We aim for quick dispatch and delivery. '),
(430, 'FACPS07MA02', 'Bumper', 'Maruti Suzuki', '800 std.', '4W', 'Body Part', NULL, NULL, 'Rear', 107, 24, 45, 3, '87087000', 'The product is a pre-owned or pre-used spare part collected form CERO Recycling centres. It has passed quality inspection at CERO. The pictures shown of the product are the actual images of the product.\nThe product comes with CERO Spares Guarantee. If the product has any genuine fitment issues / defects please inform us within 7 days from date of delivery and we will replace the same else refund the order. ', 'The product will be shipped via logistics partners appointed by CERO. We aim for quick dispatch and delivery. '),
(431, 'FACSS04MA02', 'Steering Rack Assy. (N)', 'Maruti Suzuki', '800 std.', '4W', 'Steering', NULL, NULL, NULL, 112, 19, 11, 4, '87087000', 'The product is a pre-owned or pre-used spare part collected form CERO Recycling centres. It has passed quality inspection at CERO. The pictures shown of the product are the actual images of the product.\nThe product comes with CERO Spares Guarantee. If the product has any genuine fitment issues / defects please inform us within 7 days from date of delivery and we will replace the same else refund the order. ', 'The product will be shipped via logistics partners appointed by CERO. We aim for quick dispatch and delivery. '),
(432, 'FACAT01MB33', 'Alternator', 'Mercedes-Benz', 'A160', '4W', 'Electrical', NULL, NULL, NULL, 17, 21, 15, 5, '85112010', 'The product is a pre-owned or pre-used spare part collected form CERO Recycling centres. It has passed quality inspection at CERO. The pictures shown of the product are the actual images of the product.\nThe product comes with CERO Spares Guarantee. If the product has any genuine fitment issues / defects please inform us within 7 days from date of delivery and we will replace the same else refund the order. ', 'The product will be shipped via logistics partners appointed by CERO. We aim for quick dispatch and delivery. '),
(433, 'FACDR05MB33', 'Bonnet / Hood', 'Mercedes-Benz', 'A160', '4W', 'Body Part', NULL, NULL, NULL, 1590, 144, 26, 9, '87087000', 'The product is a pre-owned or pre-used spare part collected form CERO Recycling centres. It has passed quality inspection at CERO. The pictures shown of the product are the actual images of the product.\nThe product comes with CERO Spares Guarantee. If the product has any genuine fitment issues / defects please inform us within 7 days from date of delivery and we will replace the same else refund the order. ', 'The product will be shipped via logistics partners appointed by CERO. We aim for quick dispatch and delivery. '),
(434, 'FACEL03MB33', 'Starter', 'Mercedes-Benz', 'A160', '4W', 'Electrical', NULL, NULL, NULL, 15, 25, 20, 3, '85112010', 'The product is a pre-owned or pre-used spare part collected form CERO Recycling centres. It has passed quality inspection at CERO. The pictures shown of the product are the actual images of the product.\nThe product comes with CERO Spares Guarantee. If the product has any genuine fitment issues / defects please inform us within 7 days from date of delivery and we will replace the same else refund the order. ', 'The product will be shipped via logistics partners appointed by CERO. We aim for quick dispatch and delivery. '),
(435, 'FACAC01HY02', 'AC Compressor', 'Hyundai', 'Accent', '4W', 'Air Conditioning', NULL, NULL, NULL, 14, 22, 28, 5, '84149040', 'The product is a pre-owned or pre-used spare part collected form CERO Recycling centres. It has passed quality inspection at CERO. The pictures shown of the product are the actual images of the product.\nThe product comes with CERO Spares Guarantee. If the product has any genuine fitment issues / defects please inform us within 7 days from date of delivery and we will replace the same else refund the order. ', 'The product will be shipped via logistics partners appointed by CERO. We aim for quick dispatch and delivery. '),
(436, 'FACAL01HY02', 'Condensor', 'Hyundai', 'Accent', '4W', 'Air Conditioning', NULL, NULL, NULL, 40, 82, 10, 2, '84041000', 'The product is a pre-owned or pre-used spare part collected form CERO Recycling centres. It has passed quality inspection at CERO. The pictures shown of the product are the actual images of the product.\nThe product comes with CERO Spares Guarantee. If the product has any genuine fitment issues / defects please inform us within 7 days from date of delivery and we will replace the same else refund the order. ', 'The product will be shipped via logistics partners appointed by CERO. We aim for quick dispatch and delivery. '),
(437, 'FACAL03HY02', 'Cooling Coil', 'Hyundai', 'Accent', '4W', 'Air Conditioning', NULL, NULL, NULL, 46, 47, 33, 2, '84181010', 'The product is a pre-owned or pre-used spare part collected form CERO Recycling centres. It has passed quality inspection at CERO. The pictures shown of the product are the actual images of the product.\nThe product comes with CERO Spares Guarantee. If the product has any genuine fitment issues / defects please inform us within 7 days from date of delivery and we will replace the same else refund the order. ', 'The product will be shipped via logistics partners appointed by CERO. We aim for quick dispatch and delivery. '),
(438, 'FACAL04HY02', 'Radiator', 'Hyundai', 'Accent', '4W', 'Engine and Transmission', NULL, NULL, NULL, 72, 14, 51, 4, '87087000', 'The product is a pre-owned or pre-used spare part collected form CERO Recycling centres. It has passed quality inspection at CERO. The pictures shown of the product are the actual images of the product.\nThe product comes with CERO Spares Guarantee. If the product has any genuine fitment issues / defects please inform us within 7 days from date of delivery and we will replace the same else refund the order. ', 'The product will be shipped via logistics partners appointed by CERO. We aim for quick dispatch and delivery. '),
(439, 'FACAT01HY02', 'Alternator', 'Hyundai', 'Accent', '4W', 'Electrical', NULL, NULL, NULL, 22, 26, 15, 5, '85112010', 'The product is a pre-owned or pre-used spare part collected form CERO Recycling centres. It has passed quality inspection at CERO. The pictures shown of the product are the actual images of the product.\nThe product comes with CERO Spares Guarantee. If the product has any genuine fitment issues / defects please inform us within 7 days from date of delivery and we will replace the same else refund the order. ', 'The product will be shipped via logistics partners appointed by CERO. We aim for quick dispatch and delivery. '),
(440, 'FACDR01HY02', 'Door', 'Hyundai', 'Accent', '4W', 'Body Part', NULL, 'Left', 'Front', 110, 115, 30, 25, '87087000', 'The product is a pre-owned or pre-used spare part collected form CERO Recycling centres. It has passed quality inspection at CERO. The pictures shown of the product are the actual images of the product.\nThe product comes with CERO Spares Guarantee. If the product has any genuine fitment issues / defects please inform us within 7 days from date of delivery and we will replace the same else refund the order. ', 'The product will be shipped via logistics partners appointed by CERO. We aim for quick dispatch and delivery. '),
(441, 'FACDR02HY02', 'Door', 'Hyundai', 'Accent', '4W', 'Body Part', NULL, 'Right', 'Front', 123, 105, 28, 25, '87087000', 'The product is a pre-owned or pre-used spare part collected form CERO Recycling centres. It has passed quality inspection at CERO. The pictures shown of the product are the actual images of the product.\nThe product comes with CERO Spares Guarantee. If the product has any genuine fitment issues / defects please inform us within 7 days from date of delivery and we will replace the same else refund the order. ', 'The product will be shipped via logistics partners appointed by CERO. We aim for quick dispatch and delivery. '),
(442, 'FACDR03HY02', 'Door', 'Hyundai', 'Accent', '4W', 'Body Part', NULL, 'Left', 'Rear', 110, 20, 125, 18, '87087000', 'The product is a pre-owned or pre-used spare part collected form CERO Recycling centres. It has passed quality inspection at CERO. The pictures shown of the product are the actual images of the product.\nThe product comes with CERO Spares Guarantee. If the product has any genuine fitment issues / defects please inform us within 7 days from date of delivery and we will replace the same else refund the order. ', 'The product will be shipped via logistics partners appointed by CERO. We aim for quick dispatch and delivery. '),
(443, 'FACDR04HY02', 'Door', 'Hyundai', 'Accent', '4W', 'Body Part', NULL, 'Right', 'Rear', 110, 20, 125, 18, '87087000', 'The product is a pre-owned or pre-used spare part collected form CERO Recycling centres. It has passed quality inspection at CERO. The pictures shown of the product are the actual images of the product.\nThe product comes with CERO Spares Guarantee. If the product has any genuine fitment issues / defects please inform us within 7 days from date of delivery and we will replace the same else refund the order. ', 'The product will be shipped via logistics partners appointed by CERO. We aim for quick dispatch and delivery. '),
(444, 'FACDR05HY02', 'Bonnet / Hood', 'Hyundai', 'Accent', '4W', 'Body Part', NULL, NULL, NULL, 100, 143, 15, 14, '87087000', 'The product is a pre-owned or pre-used spare part collected form CERO Recycling centres. It has passed quality inspection at CERO. The pictures shown of the product are the actual images of the product.\nThe product comes with CERO Spares Guarantee. If the product has any genuine fitment issues / defects please inform us within 7 days from date of delivery and we will replace the same else refund the order. ', 'The product will be shipped via logistics partners appointed by CERO. We aim for quick dispatch and delivery. '),
(445, 'FACDR06HY02', 'Boot / Trunk', 'Hyundai', 'Accent', '4W', 'Body Part', NULL, NULL, NULL, 120, 152, 35, 10, '87087000', 'The product is a pre-owned or pre-used spare part collected form CERO Recycling centres. It has passed quality inspection at CERO. The pictures shown of the product are the actual images of the product.\nThe product comes with CERO Spares Guarantee. If the product has any genuine fitment issues / defects please inform us within 7 days from date of delivery and we will replace the same else refund the order. ', 'The product will be shipped via logistics partners appointed by CERO. We aim for quick dispatch and delivery. '),
(446, 'FACEL03HY02', 'Starter', 'Hyundai', 'Accent', '4W', 'Electrical', NULL, NULL, NULL, 12, 22, 16, 3, '85112010', 'The product is a pre-owned or pre-used spare part collected form CERO Recycling centres. It has passed quality inspection at CERO. The pictures shown of the product are the actual images of the product.\nThe product comes with CERO Spares Guarantee. If the product has any genuine fitment issues / defects please inform us within 7 days from date of delivery and we will replace the same else refund the order. ', 'The product will be shipped via logistics partners appointed by CERO. We aim for quick dispatch and delivery. '),
(447, 'FACEL05HY02', 'Radiator fan', 'Hyundai', 'Accent', '4W', 'Engine and Transmission', NULL, NULL, NULL, 36, 43, 10, 1, '87087000', 'The product is a pre-owned or pre-used spare part collected form CERO Recycling centres. It has passed quality inspection at CERO. The pictures shown of the product are the actual images of the product.\nThe product comes with CERO Spares Guarantee. If the product has any genuine fitment issues / defects please inform us within 7 days from date of delivery and we will replace the same else refund the order. ', 'The product will be shipped via logistics partners appointed by CERO. We aim for quick dispatch and delivery. '),
(448, 'FACEW08HY02', 'Speedometer', 'Hyundai', 'Accent', '4W', 'Cabin Interior', NULL, NULL, NULL, 35, 19, 19, 1, '85112010', 'The product is a pre-owned or pre-used spare part collected form CERO Recycling centres. It has passed quality inspection at CERO. The pictures shown of the product are the actual images of the product.\nThe product comes with CERO Spares Guarantee. If the product has any genuine fitment issues / defects please inform us within 7 days from date of delivery and we will replace the same else refund the order. ', 'The product will be shipped via logistics partners appointed by CERO. We aim for quick dispatch and delivery. '),
(449, 'FACPS01HY02', 'Radiator fan', 'Hyundai', 'Accent', '4W', 'Engine and Transmission', NULL, NULL, NULL, 40, 40, 8, 1, '87087000', 'The product is a pre-owned or pre-used spare part collected form CERO Recycling centres. It has passed quality inspection at CERO. The pictures shown of the product are the actual images of the product.\nThe product comes with CERO Spares Guarantee. If the product has any genuine fitment issues / defects please inform us within 7 days from date of delivery and we will replace the same else refund the order. ', 'The product will be shipped via logistics partners appointed by CERO. We aim for quick dispatch and delivery. '),
(450, 'FACPS02HY02', 'Head Light', 'Hyundai', 'Accent', '4W', 'Lights', NULL, 'Left', NULL, 47, 24, 27, 1, '85121000', 'The product is a pre-owned or pre-used spare part collected form CERO Recycling centres. It has passed quality inspection at CERO. The pictures shown of the product are the actual images of the product.\nThe product comes with CERO Spares Guarantee. If the product has any genuine fitment issues / defects please inform us within 7 days from date of delivery and we will replace the same else refund the order. ', 'The product will be shipped via logistics partners appointed by CERO. We aim for quick dispatch and delivery. '),
(451, 'FACPS03HY02', 'Head Light', 'Hyundai', 'Accent', '4W', 'Lights', NULL, 'Right', NULL, 28, 70, 42, 1, '85121000', 'The product is a pre-owned or pre-used spare part collected form CERO Recycling centres. It has passed quality inspection at CERO. The pictures shown of the product are the actual images of the product.\nThe product comes with CERO Spares Guarantee. If the product has any genuine fitment issues / defects please inform us within 7 days from date of delivery and we will replace the same else refund the order. ', 'The product will be shipped via logistics partners appointed by CERO. We aim for quick dispatch and delivery. '),
(452, 'FACPS05HY02', 'Tail Light', 'Hyundai', 'Accent', '4W', 'Lights', NULL, 'Right', NULL, 34, 17, 35, 1, '85121000', 'The product is a pre-owned or pre-used spare part collected form CERO Recycling centres. It has passed quality inspection at CERO. The pictures shown of the product are the actual images of the product.\nThe product comes with CERO Spares Guarantee. If the product has any genuine fitment issues / defects please inform us within 7 days from date of delivery and we will replace the same else refund the order. ', 'The product will be shipped via logistics partners appointed by CERO. We aim for quick dispatch and delivery. '),
(453, 'FACPS06HY02', 'Bumper', 'Hyundai', 'Accent', '4W', 'Body Part', NULL, NULL, 'Front', 170, 70, 55, 4, '87087000', 'The product is a pre-owned or pre-used spare part collected form CERO Recycling centres. It has passed quality inspection at CERO. The pictures shown of the product are the actual images of the product.\nThe product comes with CERO Spares Guarantee. If the product has any genuine fitment issues / defects please inform us within 7 days from date of delivery and we will replace the same else refund the order. ', 'The product will be shipped via logistics partners appointed by CERO. We aim for quick dispatch and delivery. '),
(454, 'FACSS01HY02', 'Fender', 'Hyundai', 'Accent', '4W', 'Body Part', NULL, 'Left', NULL, 75, 115, 20, 3, '87087000', 'The product is a pre-owned or pre-used spare part collected form CERO Recycling centres. It has passed quality inspection at CERO. The pictures shown of the product are the actual images of the product.\nThe product comes with CERO Spares Guarantee. If the product has any genuine fitment issues / defects please inform us within 7 days from date of delivery and we will replace the same else refund the order. ', 'The product will be shipped via logistics partners appointed by CERO. We aim for quick dispatch and delivery. '),
(455, 'FACSS02HY02', 'Fender', 'Hyundai', 'Accent', '4W', 'Body Part', NULL, 'Right', NULL, 75, 115, 20, 3, '87087000', 'The product is a pre-owned or pre-used spare part collected form CERO Recycling centres. It has passed quality inspection at CERO. The pictures shown of the product are the actual images of the product.\nThe product comes with CERO Spares Guarantee. If the product has any genuine fitment issues / defects please inform us within 7 days from date of delivery and we will replace the same else refund the order. ', 'The product will be shipped via logistics partners appointed by CERO. We aim for quick dispatch and delivery. '),
(456, 'FACSS03HY02', 'Engine Holding Lower Frame or Cross Member', 'Hyundai', 'Accent', '4W', 'Engine and Transmission', NULL, NULL, NULL, 21, 48, 10, 36, '87087000', 'The product is a pre-owned or pre-used spare part collected form CERO Recycling centres. It has passed quality inspection at CERO. The pictures shown of the product are the actual images of the product.\nThe product comes with CERO Spares Guarantee. If the product has any genuine fitment issues / defects please inform us within 7 days from date of delivery and we will replace the same else refund the order. ', 'The product will be shipped via logistics partners appointed by CERO. We aim for quick dispatch and delivery. '),
(457, 'FACSS05HY02', 'Steering rack Assy. (H)', 'Hyundai', 'Accent', '4W', 'Steering', NULL, NULL, NULL, 20, 133, 22, 6, '87087000', 'The product is a pre-owned or pre-used spare part collected form CERO Recycling centres. It has passed quality inspection at CERO. The pictures shown of the product are the actual images of the product.\nThe product comes with CERO Spares Guarantee. If the product has any genuine fitment issues / defects please inform us within 7 days from date of delivery and we will replace the same else refund the order. ', 'The product will be shipped via logistics partners appointed by CERO. We aim for quick dispatch and delivery. '),
(458, 'FACSS11HY02', 'Axle', 'Hyundai', 'Accent', '4W', 'Axles', NULL, NULL, 'Rear', 70, 175, 40, 38, '87087000', 'The product is a pre-owned or pre-used spare part collected form CERO Recycling centres. It has passed quality inspection at CERO. The pictures shown of the product are the actual images of the product.\nThe product comes with CERO Spares Guarantee. If the product has any genuine fitment issues / defects please inform us within 7 days from date of delivery and we will replace the same else refund the order. ', 'The product will be shipped via logistics partners appointed by CERO. We aim for quick dispatch and delivery. '),
(459, 'FACSS13HY02', 'Axle', 'Hyundai', 'Accent', '4W', 'Axles', NULL, 'Right', 'Front', 12, 96, 12, 4, '87087000', 'The product is a pre-owned or pre-used spare part collected form CERO Recycling centres. It has passed quality inspection at CERO. The pictures shown of the product are the actual images of the product.\nThe product comes with CERO Spares Guarantee. If the product has any genuine fitment issues / defects please inform us within 7 days from date of delivery and we will replace the same else refund the order. ', 'The product will be shipped via logistics partners appointed by CERO. We aim for quick dispatch and delivery. '),
(460, 'FACSS15HY02', 'Shocker+Spring', 'Hyundai', 'Accent', '4W', 'Suspension', NULL, 'Left', 'Front', 18, 54, 18, 7, '87087000', 'The product is a pre-owned or pre-used spare part collected form CERO Recycling centres. It has passed quality inspection at CERO. The pictures shown of the product are the actual images of the product.\nThe product comes with CERO Spares Guarantee. If the product has any genuine fitment issues / defects please inform us within 7 days from date of delivery and we will replace the same else refund the order. ', 'The product will be shipped via logistics partners appointed by CERO. We aim for quick dispatch and delivery. '),
(461, 'FACSS16HY02', 'Shocker+Spring', 'Hyundai', 'Accent', '4W', 'Suspension', NULL, 'Right', 'Front', 20, 61, 20, 7, '87087000', 'The product is a pre-owned or pre-used spare part collected form CERO Recycling centres. It has passed quality inspection at CERO. The pictures shown of the product are the actual images of the product.\nThe product comes with CERO Spares Guarantee. If the product has any genuine fitment issues / defects please inform us within 7 days from date of delivery and we will replace the same else refund the order. ', 'The product will be shipped via logistics partners appointed by CERO. We aim for quick dispatch and delivery. '),
(462, 'FACSS17HY02', 'Shocker', 'Hyundai', 'Accent', '4W', 'Suspension', NULL, 'Left', 'Rear', 20, 60, 20, 2, '87087000', 'The product is a pre-owned or pre-used spare part collected form CERO Recycling centres. It has passed quality inspection at CERO. The pictures shown of the product are the actual images of the product.\nThe product comes with CERO Spares Guarantee. If the product has any genuine fitment issues / defects please inform us within 7 days from date of delivery and we will replace the same else refund the order. ', 'The product will be shipped via logistics partners appointed by CERO. We aim for quick dispatch and delivery. '),
(463, 'FACSS18HY02', 'Shocker', 'Hyundai', 'Accent', '4W', 'Suspension', NULL, 'Right', 'Rear', 20, 60, 20, 2, '87087000', 'The product is a pre-owned or pre-used spare part collected form CERO Recycling centres. It has passed quality inspection at CERO. The pictures shown of the product are the actual images of the product.\nThe product comes with CERO Spares Guarantee. If the product has any genuine fitment issues / defects please inform us within 7 days from date of delivery and we will replace the same else refund the order. ', 'The product will be shipped via logistics partners appointed by CERO. We aim for quick dispatch and delivery. '),
(464, 'FACPS13HY02', 'Fuel pump', 'Hyundai', 'Accent', '4W', 'Fuel System', NULL, NULL, NULL, 14, 24, 21, 1, '87087000', 'The product is a pre-owned or pre-used spare part collected form CERO Recycling centres. It has passed quality inspection at CERO. The pictures shown of the product are the actual images of the product.\nThe product comes with CERO Spares Guarantee. If the product has any genuine fitment issues / defects please inform us within 7 days from date of delivery and we will replace the same else refund the order. ', 'The product will be shipped via logistics partners appointed by CERO. We aim for quick dispatch and delivery. '),
(465, 'FACSS04HY02', 'Steering Rack Assy. (N)', 'Hyundai', 'Accent', '4W', 'Steering', NULL, NULL, NULL, 15, 133, 20, 6, '87087000', 'The product is a pre-owned or pre-used spare part collected form CERO Recycling centres. It has passed quality inspection at CERO. The pictures shown of the product are the actual images of the product.\nThe product comes with CERO Spares Guarantee. If the product has any genuine fitment issues / defects please inform us within 7 days from date of delivery and we will replace the same else refund the order. ', 'The product will be shipped via logistics partners appointed by CERO. We aim for quick dispatch and delivery. '),
(466, 'FACPS04HY02', 'Tail Light', 'Hyundai', 'Accent', '4W', 'Lights', NULL, 'Left', NULL, 35, 16, 33, 1, '85121000', 'The product is a pre-owned or pre-used spare part collected form CERO Recycling centres. It has passed quality inspection at CERO. The pictures shown of the product are the actual images of the product.\nThe product comes with CERO Spares Guarantee. If the product has any genuine fitment issues / defects please inform us within 7 days from date of delivery and we will replace the same else refund the order. ', 'The product will be shipped via logistics partners appointed by CERO. We aim for quick dispatch and delivery. '),
(467, 'FACEL02HY02', 'Wiper Motor ', 'Hyundai', 'Accent', '4W', 'Electrical', NULL, NULL, NULL, 18, 11, 11, 2, '87087000', 'The product is a pre-owned or pre-used spare part collected form CERO Recycling centres. It has passed quality inspection at CERO. The pictures shown of the product are the actual images of the product.\nThe product comes with CERO Spares Guarantee. If the product has any genuine fitment issues / defects please inform us within 7 days from date of delivery and we will replace the same else refund the order. ', 'The product will be shipped via logistics partners appointed by CERO. We aim for quick dispatch and delivery. ');

--
-- Indexes for dumped tables
--

--
-- Indexes for table `master_data`
--
ALTER TABLE `master_data`
  ADD PRIMARY KEY (`id`);

--
-- AUTO_INCREMENT for dumped tables
--

--
-- AUTO_INCREMENT for table `master_data`
--
ALTER TABLE `master_data`
  MODIFY `id` int(32) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=468;
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
